apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-logging-operator
  namespace: openshift-gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: devops-operators-subcharts/cluster-logging
    repoURL: 'https://github.com/edubois10/devops-operators.git'
    targetRevision: HEAD
