apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todolist
  namespace: openshift-gitops
spec:
  destination:
    namespace: devops-todo
    server: https://kubernetes.default.svc
  project: default
  source:
    path: chart
    repoURL: https://github.com/edubois10/todolist.git
    targetRevision: HEAD

